- hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start Apache
      systemd:
        name: apache2
        state: started
        enabled: true

    - name: Deploy index.html
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html
